      - name: Pre Clone
        run: |
          for script in $(find . -name "*.sh"); do
            chmod +x "$script"
          done
          ./wrt_core/pre_clone_action.sh ${{ inputs.model }}

      - name: Check after pre_clone
        run: |
          echo "====== After pre_clone_action.sh, current dir list ======"
          ls -la
          echo "====== Check if action_build exists ======"
          test -d ./action_build && echo "✅ action_build exists" || echo "❌ action_build NOT found"

      #====================【修复：mosdns，先判断action_build是否存在】====================
      - name: Fix luci-app-mosdns dependency(修复mosdns geo2txt依赖)
        run: |
          ls -la
          if [ ! -d "./action_build" ];then
            echo "❌ action_build目录不存在，pre_clone_action.sh克隆源码失败！"
            exit 1
          fi
          cd ./action_build
          # 删除原有旧mosdns、v2ray-geodata，避免冲突
          rm -rf package/luci-app-mosdns
          rm -rf feeds/packages/net/v2ray-geodata
          rm -rf package/mosdns
          # 拉取sbwml v5完整版mosdns套件（自带geo2txt,v2dat）
          git clone https://github.com/sbwml/luci-app-mosdns -b v5 package/mosdns
          #拉取geodata规则库
          git clone https://github.com/sbwml/v2ray-geodata package/v2ray-geodata
          #更新feeds，让编译系统识别新增依赖包
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cd -
